//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Properties.Langs {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DataAccess.Properties.Langs.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The email address is already in use.
        /// </summary>
        public static string errorEmailAddressInUse {
            get {
                return ResourceManager.GetString("errorEmailAddressInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The username is already in use.
        /// </summary>
        public static string errorUsernameInUse {
            get {
                return ResourceManager.GetString("errorUsernameInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Incorrect code..
        /// </summary>
        public static string globalIncorrectCode {
            get {
                return ResourceManager.GetString("globalIncorrectCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid data..
        /// </summary>
        public static string globalInvalidData {
            get {
                return ResourceManager.GetString("globalInvalidData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Too many attempts. Please request a new code..
        /// </summary>
        public static string globalTooManyAttempts {
            get {
                return ResourceManager.GetString("globalTooManyAttempts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Your profile couldn&apos;t be updated, due to an issue on our end, please try again later.
        /// </summary>
        public static string profileUpdateServerSideIssue {
            get {
                return ResourceManager.GetString("profileUpdateServerSideIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Your profile has been updated.
        /// </summary>
        public static string profileUpdateSuccess {
            get {
                return ResourceManager.GetString("profileUpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Code expired or invalid..
        /// </summary>
        public static string resetCodeExpired {
            get {
                return ResourceManager.GetString("resetCodeExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Use this code to reset your password: {0}
        ///Expires in 10 minutes..
        /// </summary>
        public static string resetEmailBody_Reset {
            get {
                return ResourceManager.GetString("resetEmailBody_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password Reset Code.
        /// </summary>
        public static string resetEmailSubject_Reset {
            get {
                return ResourceManager.GetString("resetEmailSubject_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid request..
        /// </summary>
        public static string resetInvalidRequest {
            get {
                return ResourceManager.GetString("resetInvalidRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password must be between 10 and 16 characters..
        /// </summary>
        public static string resetPasswordLengthError {
            get {
                return ResourceManager.GetString("resetPasswordLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password updated successfully..
        /// </summary>
        public static string resetPasswordUpdated {
            get {
                return ResourceManager.GetString("resetPasswordUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The account could not be created..
        /// </summary>
        public static string verifyAccountCouldNotBeCreated {
            get {
                return ResourceManager.GetString("verifyAccountCouldNotBeCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Account created. Welcome, agent!.
        /// </summary>
        public static string verifyAccountCreated {
            get {
                return ResourceManager.GetString("verifyAccountCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a There is already an active request for that email/user..
        /// </summary>
        public static string verifyAlreadyActiveRequest {
            get {
                return ResourceManager.GetString("verifyAlreadyActiveRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Your verify code is: {0}
        ///Expires in 15 minutes..
        /// </summary>
        public static string verifyEmailBodyVerify {
            get {
                return ResourceManager.GetString("verifyEmailBodyVerify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The email or username is already in use..
        /// </summary>
        public static string verifyEmailOrUserInUse {
            get {
                return ResourceManager.GetString("verifyEmailOrUserInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Verify your account.
        /// </summary>
        public static string verifyEmailSubjectVerify {
            get {
                return ResourceManager.GetString("verifyEmailSubjectVerify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid or expired request..
        /// </summary>
        public static string verifyInvalidOrExpiredRequest {
            get {
                return ResourceManager.GetString("verifyInvalidOrExpiredRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Required fields are missing..
        /// </summary>
        public static string verifyRequiredFieldsMissing {
            get {
                return ResourceManager.GetString("verifyRequiredFieldsMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a We sent you a verification code to your email..
        /// </summary>
        public static string verifyVerificationCodeSent {
            get {
                return ResourceManager.GetString("verifyVerificationCodeSent", resourceCulture);
            }
        }
    }
}
