//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ban
    {
        public System.Guid banID { get; set; }
        public System.DateTimeOffset banDatetime { get; set; }
        public string reason { get; set; }
        public System.DateTimeOffset timeout { get; set; }
        public System.Guid userID { get; set; }
    
        public virtual User User { get; set; }
    }
}
