//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PasswordReset
    {
        public System.Guid resetID { get; set; }
        public System.Guid userID { get; set; }
        public byte[] codeHash { get; set; }
        public System.DateTimeOffset expiresAt { get; set; }
        public bool used { get; set; }
        public byte attempts { get; set; }
        public System.DateTimeOffset createdAt { get; set; }
    
        public virtual User User { get; set; }
    }
}
