//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegistrationRequest
    {
        public System.Guid requestID { get; set; }
        public string email { get; set; }
        public string username { get; set; }
        public string name { get; set; }
        public string lastName { get; set; }
        public byte[] passwordHash { get; set; }
        public System.Guid passwordSalt { get; set; }
        public byte[] codeHash { get; set; }
        public byte attempts { get; set; }
        public bool used { get; set; }
        public System.DateTimeOffset createdAt { get; set; }
        public System.DateTimeOffset expiresAt { get; set; }
    }
}
