using System.Runtime.Serialization;

namespace Services.DTO.DataContract
{
    /// <summary>
    /// Used by Lobby Service to represent and identifies Game Parties (Lobbies)
    /// LobbyCode is generated by the server
    /// PartyHost is the player who Requested the creation of the Party, and who receives the LobbyCode
    /// PartyGuest are players who can join or leave the Party freely.
    /// Both player's should provide at least their playerID, username and avatarID
    /// </summary>
    [DataContract]
    public class Party
    {
        [DataMember]
        public string LobbyCode { get; set; }

        [DataMember]
        public Player PartyHost { get; set; }
        
        [DataMember]
        public Player PartyGuest { get; set; }
        
        public Party()
        {

        }

        public Party(Player partyHost, string lobbyCode)
        {
            PartyHost = partyHost;
            LobbyCode = lobbyCode;
        }

        public override bool Equals(object obj)
        {
            if (obj is Party other)
            {
                return LobbyCode.Equals(other.LobbyCode);
            }
            return false;
        }

        public override int GetHashCode()
        {
            return new { LobbyCode, PartyHost, PartyGuest }.GetHashCode();
        }
    }
}
